### ISSUE TITLE
[Bug] Shift+RMB functionality broken

### ISSUE THREAD

**Issue by AlienXtream** [joshiejack/Penguin-Lib#1]
im not 100% sure which one specifically is the problem (hence posting it on Panguin Lib issues page. not actually penguin lib itself, all functionality works with just it installed) but i think one of your harvest festival mods is breaking Shift+RMB functionality of many mods. anything that requires the player to shift right click an item in world is not working with your mods installed. 
some examples are; food pouches mod, Cofh items, Simple Magnets mod, etc.

if you could possibly look into this on your end and see if you can recreate the issue and fix it? im going to continue trying to find the specific mod that is at fault in the mean time

**Comment by AlienXtream** [comment]
ok. its not seasons. on a plus side there appear to be no obvious adverse effects of removing and re-adding the seasons module

**Comment by joshiejack** [comment]
It'll be piscary. At least that was my first thought and checked and the code suggests it would be. It's because I used to have a custom fishing rod item for my bait then changed it to any but apparently I was stupid haha with how I did it. Or rather I forgot to check that it was a fishing rod xD

**Comment by joshiejack** [comment]
Alright it should be fixed in https://www.curseforge.com/minecraft/mc-mods/piscary/files/3378582

Let me know. Thank you for reporting though. (and sorry!) Surprised noone reported it yet xD

**Comment by AlienXtream** [comment]
its fixed.

i believe this is contextually appropriate 😛 

https://tenor.com/view/gibbsslap-ncis-anthonydinozzo-gif-5368204
