### ISSUE TITLE
Unbound Tag Crash

### ISSUE THREAD

**Issue by WenXin20** [joshiejack/Penguin-Lib#4]
`Minecraft v1.16.5`
`Forge v36.1.32`
`Penguin Lib v0.4.2`

After enabling the config option `"Require clock in inventory to display the time"`, I got a crash the next time I tried to join my server. The error printed out is `java.lang.IllegalStateException: Tag penguinlib:clocks used before it was bound`.
[Crash Report](https://gist.github.com/WenXin20/f63427b3d4d845bd94acdc0b20c0d378)

**Comment by joshiejack** [comment]
Interestingly when I test it I don't get the crash. But I'm guessing it'll be a case of it trying to check the item before the item tags have been fully synced or something. Does it happen everytime? Also try loading a singleplayer game then log in to the server. I'll try to work around this, I'm just curious :P

**Comment by WenXin20** [comment]
Hmm, I'm not sure if it happens every time. I'll have to try again.
